<?php

namespace AppBundle\Repository;

/**
 * CategoryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
