<?php

namespace AppBundle\Repository;

/**
 * CourtcaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourtcaseRepository extends \Doctrine\ORM\EntityRepository
{
}
