<?php

namespace AppBundle\Repository;

/**
 * EducationLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
