<?php

namespace AppBundle\Repository;

/**
 * EmailCommRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailCommRepository extends \Doctrine\ORM\EntityRepository
{
}
