<?php

namespace AppBundle\Repository;

/**
 * JusticeTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JusticeTitleRepository extends \Doctrine\ORM\EntityRepository
{
}
