<?php

namespace AppBundle\Repository;

/**
 * PredictionJudgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredictionJudgeRepository extends \Doctrine\ORM\EntityRepository
{
}
